---
- name: Install yum-utils|workaround for dnf
  yum: name=yum-utils state=present
  sudo: yes

- name: Update system
  dnf: name=* state=latest
  remote_user: fedora
  sudo: yes

- name: Install prerequisites
  dnf: name={{ item }} state=present
  with_items:
    - vim
    - git
  sudo: yes
